Homework 4
egavolk/smart-home-2020 pull request #4
Opened 2020-03-26 06:56 UTC by egavolk

2020-03-30 15:29 UTC, a-ivanov requested changes

2020-03-30 15:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/application/Application.java
> +        EventManager eventManager = context.getBean(EventManager.class);
См. текст задания в презентации - надо использовать SensorEventsManager вместо EventManager

2020-03-30 15:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/events/EventManagerCCAdapter.java
> +import ru.sbt.mipt.oop.smarthome.events.handlers.EventHandler;
Это должен быть интерфейс обработчика из сторонней библиотеки.

2020-03-30 15:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smarthome/events/CCEventAdapter.java
> +    private Map<String, EventType> getTypeByCCString = new HashMap<>();
Сделайте мапу аргументом в конструкторе. Ее можно конфигурировать отдельным бином в спринге.

2020-03-31 19:37 UTC, egavolk commented on src/main/java/ru/sbt/mipt/oop/application/Application.java
> +        EventManager eventManager = context.getBean(EventManager.class);
Мне кажется, что мой `EventManager` это как раз и есть `SensorEventsManager` из задания. Если это не так, то объясните, пожалуйста, в чем разница. А переименовывать мой `EventManager` в `SensorEventsManager` нехорошо, так как он обрабатывает все события(я разделяю события на `SensorEvent` и `AlarmEvent`) и все они прилетают в единый `EventManager`

2020-04-03 11:49 UTC, a-ivanov approved these changes

2020-04-04 16:06 UTC, merged